services:
  postgres:
    image: postgres:15-alpine
    container_name: poke-postgres
    environment:
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: pokemon123
      POSTGRES_DB: pokemon_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pokemon"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: poke-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pokemon.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: poke-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://pokemon:pokemon123@postgres:5432/pokemon_db?schema=public
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET:-536157ed9d93cb3a5502f1d2f81641c5}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: poke-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_GRAPHQL_URL: http://localhost:3001/api/graphql
      NODE_ENV: development
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
  pgadmin_data:

